Repository LLNL/axom, pull requests merged in 2020-02, with the labels that each got.

#160 Axom logo
  README.md
  share/axom/logo/axom_logo.png
Labels: Documentation

#155 Support for CI Testing using Azure Pipelines/Docker
  azure-pipelines.yml
  host-configs/docker/docker-linux-ubuntu16.04-x86_64-clang@4.0.0.cmake
  host-configs/docker/docker-linux-ubuntu16.04-x86_64-clang@5.0.0.cmake
  host-configs/docker/docker-linux-ubuntu16.04-x86_64-clang@6.0.0.cmake
  host-configs/docker/docker-linux-ubuntu16.04-x86_64-gcc@6.1.0.cmake
  host-configs/docker/docker-linux-ubuntu16.04-x86_64-gcc@7.3.0.cmake
  host-configs/docker/docker-linux-ubuntu16.04-x86_64-gcc@8.1.0.cmake
  scripts/azure-pipelines/linux-build_and_test.sh
  scripts/docker/README.md
  scripts/docker/dockerfile_clang-4
  scripts/docker/dockerfile_clang-5
  scripts/docker/dockerfile_clang-6
  scripts/docker/dockerfile_gcc-6
  scripts/docker/dockerfile_gcc-7
  scripts/docker/dockerfile_gcc-8
  scripts/uberenv/spack_configs/docker/compilers.yaml
  scripts/uberenv/spack_configs/docker/packages.yaml
Labels: CI, TPL

#163 Use CudaKernelFixed and tread_direct policies
  RELEASE-NOTES.md
  src/axom/mint/execution/internal/structured_exec.hpp
Labels: GPU, Mint, bug

#167 Attempt to fix CI tests of sidre_lulesh by changing number of ctest threads
  src/axom/sidre/examples/lulesh2/CMakeLists.txt
Labels: CI, Testing

#165 Set boolean option so job fails when tests fail
  azure-pipelines.yml
Labels: CI, Testing

#173 Quick update to docs
  scripts/bamboo/install_webdocs.sh
  scripts/bamboo/queue_build.py
  scripts/llnl_scripts/find_unused_tpl_dirs.py
  src/docs/sphinx/dev_guide/bamboo.rst
  src/docs/sphinx/dev_guide/component_org.rst
  src/docs/sphinx/dev_guide/continuous_integration.rst
  src/docs/sphinx/dev_guide/dev_summary.rst
  src/docs/sphinx/dev_guide/github.rst
  src/docs/sphinx/dev_guide/index.rst
  src/docs/sphinx/dev_guide/jira-issue.dot
  src/docs/sphinx/dev_guide/jira-issue.png
  src/docs/sphinx/dev_guide/jira.rst
  src/docs/sphinx/dev_guide/misc_tasks.rst
  src/docs/sphinx/dev_guide/pull_requests.rst
  src/docs/sphinx/quickstart_guide/config_build.rst
  src/docs/sphinx/quickstart_guide/the_code.rst
  src/docs/sphinx/quickstart_guide/zero_to_axom.rst
Labels: Documentation

#176 Axom Memory Management API Updates
  RELEASE-NOTES.md
  src/axom/core/execution/internal/cuda_exec.hpp
  src/axom/core/execution/internal/omp_exec.hpp
  src/axom/core/execution/internal/seq_exec.hpp
  src/axom/core/memory_management.hpp
  src/axom/core/tests/core_execution_for_all.cpp
  src/axom/core/tests/core_execution_space.cpp
  src/axom/core/tests/core_memory_management.cpp
  src/axom/mint/examples/user_guide/mint_getting_started.cpp
  src/axom/mint/tests/mint_execution_cell_traversals.cpp
  src/axom/mint/tests/mint_execution_face_traversals.cpp
  src/axom/mint/tests/mint_execution_node_traversals.cpp
  src/axom/sidre/core/Buffer.cpp
  src/axom/sidre/core/Group.cpp
  src/axom/sidre/core/Group.hpp
  src/axom/sidre/tests/sidre_buffer.cpp
  src/axom/sidre/tests/sidre_group.cpp
  src/axom/sidre/tests/sidre_view.cpp
  src/axom/spin/BVH.hpp
  src/axom/spin/tests/spin_bvh.cpp
  src/thirdparty/tests/raja_smoke.cpp
Labels: App Integration, Core, GPU

#172 Generic BVH Traversal
  src/axom/spin/BVH.hpp
  src/axom/spin/CMakeLists.txt
  src/axom/spin/internal/linear_bvh/BVH_impl.hpp
  src/axom/spin/internal/linear_bvh/QueryAccessor.hpp
  src/axom/spin/internal/linear_bvh/TraversalPredicates.hpp
  src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
  src/axom/spin/internal/linear_bvh/bvh_traverse.hpp
  src/axom/spin/internal/linear_bvh/emit_bvh.hpp
  src/axom/spin/tests/spin_bvh.cpp
Labels: GPU, Spin
