Repository LLNL/axom, pull requests merged in 2021-06, with the labels that each got.

#573 LinearBVH cleanup
  src/axom/primal/geometry/BoundingBox.hpp
  src/axom/primal/geometry/NumericArray.hpp
  src/axom/primal/geometry/Point.hpp
  src/axom/primal/geometry/Vector.hpp
  src/axom/spin/CMakeLists.txt
  src/axom/spin/MortonIndex.hpp
  src/axom/spin/internal/linear_bvh/BVHData.hpp
  src/axom/spin/internal/linear_bvh/BVH_impl.hpp
  src/axom/spin/internal/linear_bvh/RadixTree.hpp
  src/axom/spin/internal/linear_bvh/TraversalPredicates.hpp
  src/axom/spin/internal/linear_bvh/aabb.hpp
  src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
  src/axom/spin/internal/linear_bvh/bvh_vtkio.hpp
  src/axom/spin/internal/linear_bvh/emit_bvh.hpp
  src/axom/spin/internal/linear_bvh/range.hpp
  src/axom/spin/internal/linear_bvh/vec.hpp
  src/axom/spin/tests/spin_bvh.cpp
Labels: GPU, Primal, Spin

#576 Fix typo in conflict
  scripts/spack/packages/axom/package.py
Labels: Build system, TPL, bug, invalid

#577 LinearBVH refactoring #2
  src/axom/primal/geometry/BoundingBox.hpp
  src/axom/primal/geometry/Point.hpp
  src/axom/primal/geometry/Ray.hpp
  src/axom/primal/operators/detail/intersect_ray_impl.hpp
  src/axom/primal/operators/intersect.hpp
  src/axom/spin/CMakeLists.txt
  src/axom/spin/internal/linear_bvh/BVHData.hpp
  src/axom/spin/internal/linear_bvh/BVH_impl.hpp
  src/axom/spin/internal/linear_bvh/QueryAccessor.hpp
  src/axom/spin/internal/linear_bvh/TraversalPredicates.hpp
  src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
  src/axom/spin/internal/linear_bvh/bvh_traverse.hpp
  src/axom/spin/internal/linear_bvh/bvh_vtkio.hpp
  src/axom/spin/internal/linear_bvh/emit_bvh.hpp
  src/axom/spin/internal/linear_bvh/math.hpp
  src/axom/spin/tests/spin_bvh.cpp
Labels: GPU, Primal, Spin

#578 Bump TPLs to conduit 0.7.2
  .uberenv_config.json
  azure-pipelines.yml
  host-configs/docker/docker-linux-ubuntu16.04-ivybridge-gcc@8.1.0.cmake
  host-configs/docker/docker-linux-ubuntu18.04-x86_64-clang@10.0.0.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@9.0.0_upstream_xlf.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1_coral.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1_nvcc.cmake
  host-configs/ruby-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/ruby-toss_3_x86_64_ib-clang@9.0.0.cmake
  host-configs/ruby-toss_3_x86_64_ib-gcc@8.1.0.cmake
  host-configs/ruby-toss_3_x86_64_ib-gcc@8.1_no_fortran.cmake
  host-configs/ruby-toss_3_x86_64_ib-intel@18.0.2.cmake
  host-configs/ruby-toss_3_x86_64_ib-intel@19.0.4.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@9.0.0_upstream_xlf.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_coral.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_nvcc.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@9.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1_no_fortran.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.4.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-clang@8.0.1_nvcc_xlf.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-clang@9.0.0_upstream_xlf.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-gcc@7.3.1.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_coral.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_nvcc.cmake
  scripts/docker/dockerfile_clang-10
  scripts/docker/dockerfile_gcc-8
  scripts/spack/configs/blueos_3_ppc64le_ib/packages.yaml
  scripts/spack/configs/blueos_3_ppc64le_ib_p9/packages.yaml
  scripts/spack/configs/docker/ubuntu16/packages.yaml
  scripts/spack/configs/docker/ubuntu18/packages.yaml
  scripts/spack/configs/toss_3_x86_64_ib/packages.yaml
  src/axom/core/examples/CMakeLists.txt
  src/axom/core/tests/CMakeLists.txt
  src/axom/inlet/examples/CMakeLists.txt
  src/axom/inlet/tests/CMakeLists.txt
  src/axom/lumberjack/examples/CMakeLists.txt
  src/axom/lumberjack/tests/CMakeLists.txt
  src/axom/mint/examples/CMakeLists.txt
  src/axom/mint/tests/CMakeLists.txt
  src/axom/primal/examples/CMakeLists.txt
  src/axom/primal/tests/CMakeLists.txt
  src/axom/quest/examples/CMakeLists.txt
  src/axom/quest/tests/CMakeLists.txt
  src/axom/sidre/examples/CMakeLists.txt
  src/axom/sidre/examples/spio/CMakeLists.txt
  src/axom/sidre/tests/CMakeLists.txt
  src/axom/sidre/tests/spio/CMakeLists.txt
  src/axom/slam/examples/CMakeLists.txt
  src/axom/slam/tests/CMakeLists.txt
  src/axom/slic/examples/CMakeLists.txt
  src/axom/slic/tests/CMakeLists.txt
  src/axom/spin/examples/CMakeLists.txt
  src/axom/spin/tests/CMakeLists.txt
Labels: TPL, Testing

#586 Use fmtlib to produce mint VTK output
  src/axom/mint/utils/vtk_utils.cpp
Labels: Mint

#585 Adds c2c library as an optional TPL for Axom
  RELEASE-NOTES.md
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@9.0.0_upstream_xlf.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1_coral.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1_nvcc.cmake
  host-configs/ruby-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/ruby-toss_3_x86_64_ib-clang@9.0.0.cmake
  host-configs/ruby-toss_3_x86_64_ib-gcc@8.1.0.cmake
  host-configs/ruby-toss_3_x86_64_ib-gcc@8.1_no_fortran.cmake
  host-configs/ruby-toss_3_x86_64_ib-intel@18.0.2.cmake
  host-configs/ruby-toss_3_x86_64_ib-intel@19.0.4.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@9.0.0_upstream_xlf.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_coral.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_nvcc.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@9.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1_no_fortran.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.4.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-clang@8.0.1_nvcc_xlf.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-clang@9.0.0_upstream_xlf.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-gcc@7.3.1.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_coral.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_nvcc.cmake
  scripts/llnl_scripts/batch_scripts/bsub_llnl_rz_blueos_all_compilers.sh
  scripts/llnl_scripts/batch_scripts/msub_llnl_rz_toss3_all_compilers.sh
  scripts/spack/packages/axom/package.py
  scripts/spack/packages/c2c/package.py
  scripts/spack/specs.json
  src/axom/config.hpp.in
  src/axom/core/examples/core_utilities.cpp
  src/axom/core/tests/utils_config.cpp
  src/axom/core/utilities/About.cpp
  src/cmake/AxomConfig.cmake
  src/cmake/axom-config.cmake.in
  src/cmake/thirdparty/FindC2C.cmake
  src/cmake/thirdparty/SetupAxomThirdParty.cmake
  src/docs/sphinx/dev_guide/component_org.rst
  src/docs/sphinx/dev_guide/continuous_integration.rst
  src/docs/sphinx/quickstart_guide/config_build.rst
  src/thirdparty/tests/CMakeLists.txt
  src/thirdparty/tests/c2c_smoke.cpp
Labels: Build system, TPL

#588 Marks several static members with AXOM_EXPORT after changes in #578
  src/axom/mint/mesh/CurvilinearMesh.hpp
  src/axom/mint/mesh/RectilinearMesh.hpp
  src/axom/sidre/core/Group.hpp
  src/axom/slam/BitSet.hpp
  src/axom/slam/policies/SubsettingPolicies.hpp
Labels: Build system, Windows, bug

#587 Add new schema to generated Blueprint index
  RELEASE-NOTES.md
  src/axom/sidre/core/DataStore.cpp
  src/axom/sidre/examples/sidre_generateindex.cpp
  src/axom/sidre/spio/IOManager.cpp
  src/axom/sidre/spio/IOManager.hpp
Labels: Spio, User Request, enhancement

#592 Small typo in Spack package
  host-configs/docker/docker-linux-ubuntu16.04-ivybridge-gcc@8.1.0.cmake
  host-configs/docker/docker-linux-ubuntu18.04-x86_64-clang@10.0.0.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@9.0.0_upstream_xlf.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1_coral.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1_nvcc.cmake
  host-configs/ruby-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/ruby-toss_3_x86_64_ib-clang@9.0.0.cmake
  host-configs/ruby-toss_3_x86_64_ib-gcc@8.1_no_fortran.cmake
  host-configs/ruby-toss_3_x86_64_ib-intel@18.0.2.cmake
  host-configs/ruby-toss_3_x86_64_ib-intel@19.0.4.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@9.0.0_upstream_xlf.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_coral.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_nvcc.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@9.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1_no_fortran.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.4.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-clang@8.0.1_nvcc_xlf.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-clang@9.0.0_upstream_xlf.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-gcc@7.3.1.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_coral.cmake
  host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_nvcc.cmake
  scripts/spack/packages/axom/package.py
Labels: TPL, invalid

#593 Remove blueos requirement on cuda logic
  scripts/spack/packages/axom/package.py
Labels: Build system, cuda

#595 Bugfix for empty string literals in XLF
  src/axom/mint/mesh/CurvilinearMesh.hpp
  src/axom/mint/mesh/RectilinearMesh.hpp
  src/axom/sidre/tests/sidre_group_F.F
  src/axom/sidre/tests/sidre_view_F.f
Labels: Fortan, bug, compiler

#596 Fix compiler checks that were mistakenly removed
  scripts/spack/packages/axom/package.py
Labels: TPL, bug, cuda

#599 Moves some MSVC-related pragmas out of config.hpp.in
  RELEASE-NOTES.md
  src/axom/config.hpp.in
  src/cmake/AxomConfig.cmake
Labels: App Integration, Build system, Fortan, Windows, compiler

#597 Upgrade our vcpkg usage
  .uberenv_config.json
  RELEASE-NOTES.md
  scripts/vcpkg_ports/axom/CONTROL
  scripts/vcpkg_ports/axom/portfile.cmake
  scripts/vcpkg_ports/axom/vcpkg.json
  scripts/vcpkg_ports/blt/CONTROL
  scripts/vcpkg_ports/blt/portfile.cmake
  scripts/vcpkg_ports/blt/vcpkg.json
  scripts/vcpkg_ports/conduit/CONTROL
  scripts/vcpkg_ports/conduit/hdf5-1-12.patch
  scripts/vcpkg_ports/conduit/portfile.cmake
  scripts/vcpkg_ports/conduit/setup_deps_vcpkg_triplet.patch
  scripts/vcpkg_ports/conduit/vcpkg.json
  scripts/vcpkg_ports/mfem/CONTROL
  scripts/vcpkg_ports/mfem/portfile.cmake
  scripts/vcpkg_ports/mfem/vcpkg.json
Labels: Build system, TPL, Windows, maintenance

#598 LinearBVH optimizations
  src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
  src/axom/spin/internal/linear_bvh/bvh_traverse.hpp
Labels: GPU, Spin
