Repository LLNL/axom, pull requests merged in 2021-04, with the labels that each got.

#479 Detect unexpected entries in input files
  RELEASE-NOTES.md
  src/axom/inlet/ConduitReader.cpp
  src/axom/inlet/ConduitReader.hpp
  src/axom/inlet/Container.cpp
  src/axom/inlet/Container.hpp
  src/axom/inlet/Inlet.hpp
  src/axom/inlet/LuaReader.cpp
  src/axom/inlet/LuaReader.hpp
  src/axom/inlet/Reader.hpp
  src/axom/inlet/docs/sphinx/verification.rst
  src/axom/inlet/examples/nested_structs.cpp
  src/axom/inlet/tests/inlet_Reader.cpp
  src/axom/inlet/tests/inlet_object.cpp
Labels: Inlet, enhancement

#516 Bugfix/white238/fixdevtools
  scripts/spack/devtools.json
  scripts/spack/devtools_configs/blueos_3_ppc64le_ib/packages.yaml
  scripts/spack/devtools_configs/blueos_3_ppc64le_ib_p9/packages.yaml
  scripts/spack/devtools_configs/toss_3_x86_64_ib/packages.yaml
Labels: Documentation, TPL, maintenance

#518 Fix typo
  .gitlab-ci.yml
  .gitlab/build_lassen.yml
  .gitlab/build_ruby.yml
  src/docs/sphinx/dev_guide/release.rst
Labels: Documentation, Release, Software process, enhancement, good first issue, invalid, maintenance

#526 Attempt to fix the full build jobs
  .gitlab-ci.yml
  .gitlab/build_ruby.yml
Labels: CI, bug

#527 Fix full build rule
  .gitlab-ci.yml
  .gitlab/build_lassen.yml
  .gitlab/build_ruby.yml
  scripts/llnl_scripts/llnl_lc_build_tools.py
Labels: CI, bug

#392 Incorporate BLT's new blt_import_library macro
  src/axom/CMakeLists.txt
  src/axom/core/examples/CMakeLists.txt
  src/axom/core/tests/CMakeLists.txt
  src/axom/lumberjack/tests/CMakeLists.txt
  src/axom/mint/examples/CMakeLists.txt
  src/axom/mint/tests/CMakeLists.txt
  src/axom/primal/examples/CMakeLists.txt
  src/axom/primal/tests/CMakeLists.txt
  src/axom/quest/examples/CMakeLists.txt
  src/axom/quest/tests/CMakeLists.txt
  src/axom/sidre/examples/CMakeLists.txt
  src/axom/sidre/tests/CMakeLists.txt
  src/axom/sidre/tests/spio/CMakeLists.txt
  src/axom/slam/examples/CMakeLists.txt
  src/axom/slam/tests/CMakeLists.txt
  src/axom/spin/examples/CMakeLists.txt
  src/axom/spin/tests/CMakeLists.txt
  src/cmake/thirdparty/SetupAxomThirdParty.cmake
  src/cmake/thirdparty/SetupHDF5.cmake
Labels: Build system, TPL

#529 Small spack package fixes
  scripts/spack/packages/axom/package.py
Labels: Build system, TPL, bug
