Repository LLNL/axom, pull requests merged in 2022-11, with the labels that each got.

#952 Use service user for gitlab ci
  .gitlab-ci.yml
Labels: CI

#958 Document call-back functors for traversing BVH
  src/axom/spin/internal/linear_bvh/bvh_traverse.hpp
  src/axom/spin/policy/LinearBVH.hpp
Labels: Documentation, Spin, GPU, cuda

#962 Advised fix for Tioga CI problems
  .gitlab/build_tioga.yml
Labels: CI

#960 sets EXPORT_NAME of the fmt target to axom::fmt to avoid conflicts in…
  src/thirdparty/CMakeLists.txt
Labels: bug, App Integration, Build system, User Request, usability

#965 Small documentation fixes accidentally omitted from an earlier PR.
  RELEASE-NOTES.md
  src/axom/core/Array.hpp
Labels: Documentation
