Repository LLNL/axom, pull requests merged in 2023-11, with the labels that each got.

#1207 Build configs with +scr
  host-configs/quartz-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/quartz-toss_4_x86_64_ib-gcc@10.3.1.cmake
  host-configs/quartz-toss_4_x86_64_ib-intel@2022.1.0.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-gcc@10.3.1.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-intel@2022.1.0.cmake
  host-configs/rzwhippet-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/rzwhippet-toss_4_x86_64_ib-gcc@10.3.1.cmake
  host-configs/rzwhippet-toss_4_x86_64_ib-intel@2022.1.0.cmake
  scripts/spack/specs.json
  src/cmake/thirdparty/SetupAxomThirdParty.cmake
Labels: TPL, CI

#1214 Various clean-up for downstream projects
  src/axom/CMakeLists.txt
  src/cmake/axom-config.cmake.in
Labels: enhancement, TPL, Build system, User Request

#1201 Update outdated documentation for MarchingCubes
  src/axom/quest/docs/sphinx/isosurface_detection.rst
Labels: Documentation

#1217 Move to service user and new bank on lassen
  .gitlab/build_lassen.yml
  .gitlab/build_tioga.yml
Labels: CI

#1212 Intersection-based Primal improvements
  RELEASE-NOTES.md
  src/axom/primal/examples/hex_tet_volume.cpp
  src/axom/primal/geometry/Polyhedron.hpp
  src/axom/primal/geometry/Tetrahedron.hpp
  src/axom/primal/operators/clip.hpp
  src/axom/primal/operators/detail/clip_impl.hpp
  src/axom/primal/operators/intersection_volume.hpp
  src/axom/primal/tests/primal_clip.cpp
  src/axom/primal/tests/primal_hexahedron.cpp
  src/axom/primal/tests/primal_tetrahedron.cpp
  src/axom/quest/IntersectionShaper.hpp
Labels: Primal

#1202 Doc/capps2/release edits
  src/docs/sphinx/dev_guide/release.rst
Labels: Release, Build system, Documentation

#1225 Refactor/gunney/runtime policy
  src/axom/core/CMakeLists.txt
  src/axom/core/execution/execution_space.hpp
  src/axom/core/execution/runtime_policy.hpp
  src/axom/quest/DistributedClosestPoint.hpp
  src/axom/quest/IntersectionShaper.hpp
  src/axom/quest/MarchingCubes.cpp
  src/axom/quest/MarchingCubes.hpp
  src/axom/quest/examples/quest_distributed_distance_query_example.cpp
  src/axom/quest/examples/quest_marching_cubes_example.cpp
  src/axom/quest/examples/shaping_driver.cpp
  src/axom/quest/tests/quest_intersection_shaper.cpp
  src/docs/doxygen/Doxyfile.in
Labels: Core, Quest
