Repository LLNL/axom, pull requests merged in 2023-02, with the labels that each got.

#1016 Fix doxygen on ReadTheDocs (+ return to srun for MPI tests on tioga)
  host-configs/tioga-toss_4_x86_64_ib_cray-clang@14.0.0_hip.cmake
  src/conf.py
Labels: CI, Documentation

#1023 Turn back on allow_failure for tioga jobs
  .gitlab/build_tioga.yml
Labels: bug, invalid, Testing, CI, Software process

#1021 Updates conduit dependency to conduit@0.8.6
  RELEASE-NOTES.md
  azure-pipelines.yml
  host-configs/docker/clang@10.0.0.cmake
  host-configs/docker/gcc@11.1.0.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake
  host-configs/ruby-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/ruby-toss_3_x86_64_ib-clang@9.0.0.cmake
  host-configs/ruby-toss_3_x86_64_ib-gcc@8.1.0_nofortran.cmake
  host-configs/ruby-toss_3_x86_64_ib-gcc@8.3.1.cmake
  host-configs/ruby-toss_3_x86_64_ib-intel@19.0.4.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@9.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0_nofortran.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.3.1.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.4.cmake
  host-configs/rzvernal-toss_4_x86_64_ib_cray-clang@14.0.0_hip.cmake
  host-configs/tioga-toss_4_x86_64_ib_cray-clang@14.0.0_hip.cmake
  scripts/llnl_scripts/llnl_lc_build_tools.py
  scripts/spack/configs/blueos_3_ppc64le_ib_p9/packages.yaml
  scripts/spack/configs/darwin/packages.yaml
  scripts/spack/configs/docker/ubuntu20/packages.yaml
  scripts/spack/configs/toss_3_x86_64_ib/packages.yaml
  scripts/spack/configs/toss_4_x86_64_ib/packages.yaml
  scripts/spack/configs/toss_4_x86_64_ib_cray/packages.yaml
  scripts/spack/devtools_configs/toss_3_x86_64_ib/packages.yaml
  scripts/spack/packages/axom/package.py
  scripts/spack/packages/conduit/bpparametis.patch
  scripts/spack/packages/conduit/package.py
  scripts/vcpkg_ports/conduit/portfile.cmake
  scripts/vcpkg_ports/conduit/vcpkg.json
  src/examples/using-with-cmake/CMakeLists.txt
Labels: TPL, maintenance

#1015 Non-unit Array element spacing
  src/axom/core/Array.hpp
  src/axom/core/ArrayBase.hpp
  src/axom/core/ArrayView.hpp
  src/axom/core/docs/sphinx/core_containers.rst
  src/axom/core/examples/core_containers.cpp
  src/axom/core/tests/core_array.hpp
  src/axom/mint/utils/ExternalArray.hpp
  src/axom/sidre/core/Array.hpp
Labels: enhancement, Core

#1025 Bugfix for importing caliper-enabled mfem in cuda configs
  src/axom/primal/tests/primal_curved_polygon.cpp
  src/axom/primal/tests/primal_orientedboundingbox.cpp
  src/axom/spin/tests/spin_bvh.cpp
  src/cmake/thirdparty/SetupAxomThirdParty.cmake
Labels: bug, App Integration, TPL, Build system

#1026 Further improves import logic for caliper-enabled mfem target
  RELEASE-NOTES.md
  src/cmake/thirdparty/FindROCTracer.cmake
  src/cmake/thirdparty/SetupAxomThirdParty.cmake
Labels: bug, TPL, Build system

#1020 Polyhedron::getFaces() public function
  src/axom/primal/geometry/Polyhedron.hpp
  src/axom/primal/tests/primal_polyhedron.cpp
Labels: Primal, User Request

#1031 UniformGrid memory fixes
  .gitlab/build_lassen.yml
  src/axom/spin/UniformGrid.hpp
  src/axom/spin/policy/UniformGridStorage.hpp
  src/axom/spin/tests/spin_uniform_grid.cpp
Labels: bug, Testing, Spin

#1032 Update config.yaml to modern spec.format syntax
  scripts/spack/configs/config.yaml
  scripts/spack/devtools_configs/config.yaml
Labels: TPL

#1034 Bugfixes for bugfixes
  src/axom/primal/tests/primal_orientedboundingbox.cpp
  src/axom/spin/tests/spin_bvh.cpp
  src/cmake/thirdparty/FindLUA.cmake
Labels: bug
