Repository LLNL/axom, pull requests merged in 2024-05, with the labels that each got.

#1335 Remove caching of FOUND variables
  RELEASE-NOTES.md
  src/cmake/thirdparty/SetupAxomThirdParty.cmake
Labels: bug, Build system

#1340 Harden CMake find_*
  RELEASE-NOTES.md
  src/cmake/AxomMacros.cmake
  src/cmake/axom-config.cmake.in
  src/cmake/thirdparty/SetupAxomThirdParty.cmake
Labels: bug, App Integration, TPL, Build system, User Request

#1316 Set default allocator id to device instead of unified for CUDA and HIP execution policies
  RELEASE-NOTES.md
  src/axom/core/examples/core_acceleration.cpp
  src/axom/core/execution/internal/cuda_exec.hpp
  src/axom/core/execution/internal/hip_exec.hpp
  src/axom/core/tests/core_array_for_all.hpp
  src/axom/core/tests/core_execution_for_all.hpp
  src/axom/core/tests/core_execution_space.hpp
  src/axom/mint/tests/mint_execution_cell_traversals.cpp
  src/axom/mint/tests/mint_execution_face_traversals.cpp
  src/axom/mint/tests/mint_execution_node_traversals.cpp
  src/axom/primal/tests/primal_boundingbox.cpp
  src/axom/primal/tests/primal_clip.cpp
  src/axom/primal/tests/primal_numeric_array.cpp
  src/axom/primal/tests/primal_point.cpp
  src/axom/primal/tests/primal_polyhedron.cpp
  src/axom/primal/tests/primal_vector.cpp
  src/axom/primal/tests/primal_zip.cpp
  src/axom/quest/DistributedClosestPoint.cpp
  src/axom/quest/IntersectionShaper.hpp
  src/axom/quest/detail/Discretize_detail.hpp
  src/axom/quest/detail/DistributedClosestPointImpl.hpp
  src/axom/quest/examples/quest_distributed_distance_query_example.cpp
  src/axom/quest/tests/quest_discretize.cpp
  src/axom/quest/tests/quest_signed_distance.cpp
  src/axom/spin/tests/spin_bvh.cpp
  src/axom/spin/tests/spin_implicit_grid.cpp
  src/tools/mesh_tester.cpp
Labels: Core, Quest, Primal, GPU

#1346 Gitlab batch runners
  .gitlab-ci.yml
  .gitlab/build_lassen.yml
  .gitlab/build_quartz.yml
  .gitlab/build_rzansel.yml
  .gitlab/build_rzgenie.yml
  .gitlab/build_tioga.yml
Labels: CI
