Repository LLNL/axom, pull requests merged in 2024-03, with the labels that each got.

#1286 Fixes memory leaks in axom
  RELEASE-NOTES.md
  src/axom/core/Array.hpp
  src/axom/core/numerics/Matrix.hpp
  src/axom/core/tests/core_array.hpp
  src/axom/core/tests/core_map.hpp
  src/axom/core/tests/numerics_matrix.hpp
  src/axom/inlet/VariantKey.hpp
  src/axom/klee/tests/KleeMatchers.hpp
  src/axom/lumberjack/Message.cpp
  src/axom/lumberjack/Message.hpp
  src/axom/lumberjack/tests/lumberjack_BinaryCommunicator.hpp
  src/axom/lumberjack/tests/lumberjack_Message.hpp
  src/axom/lumberjack/tests/lumberjack_RootCommunicator.hpp
  src/axom/mint/examples/user_guide/mint_getting_started.cpp
  src/axom/mint/execution/internal/for_all_cells.hpp
  src/axom/mint/tests/mint_fem_single_fe.cpp
  src/axom/mint/tests/mint_mesh_connectivity_array.cpp
  src/axom/multimat/multimat.cpp
  src/axom/primal/operators/detail/clip_impl.hpp
  src/axom/primal/tests/primal_curved_polygon.cpp
  src/axom/quest/SamplingShaper.hpp
  src/axom/quest/interface/internal/QuestHelpers.hpp
  src/axom/quest/tests/quest_c2c_reader.cpp
  src/axom/quest/tests/quest_inout_interface.cpp
  src/axom/quest/tests/quest_point_in_cell_mfem.cpp
  src/axom/sidre/core/MFEMSidreDataCollection.cpp
  src/axom/sidre/core/MFEMSidreDataCollection.hpp
  src/axom/sidre/examples/lulesh2/lulesh-init.cc
  src/axom/sidre/examples/lulesh2/lulesh.cc
  src/axom/sidre/examples/lulesh2/lulesh.h
  src/axom/sidre/examples/sidre_createdatastore.cpp
  src/axom/sidre/examples/sidre_generateindex.cpp
  src/axom/sidre/examples/sidre_mfem_datacollection_restart.cpp
  src/axom/sidre/tests/sidre_collections.cpp
  src/axom/sidre/tests/sidre_group.cpp
  src/axom/sidre/tests/sidre_group_C.cpp
  src/axom/sidre/tests/sidre_mfem_datacollection.cpp
  src/axom/sidre/tests/sidre_opaque_C.cpp
  src/axom/sidre/tests/sidre_view.cpp
  src/axom/sidre/tests/spio/spio_basic.hpp
  src/axom/sidre/tests/spio/spio_main.cpp
  src/axom/sidre/tests/spio/spio_parallel.hpp
  src/axom/sidre/tests/spio/spio_serial.hpp
  src/axom/slam/examples/lulesh2.0.3/lulesh-init.cpp
  src/axom/slam/examples/lulesh2.0.3/lulesh.hpp
  src/axom/slam/mesh_struct/IA_impl.hpp
  src/axom/slic/core/Logger.cpp
  src/axom/slic/core/Logger.hpp
  src/axom/spin/tests/spin_bvh.cpp
  src/tools/data_collection_util.cpp
Labels: bug, maintenance, memory

#1288 Bugfix for intermittent failure of quest_inout_interface Fortran example
  src/axom/quest/examples/quest_inout_interface.F
  src/axom/quest/interface/inout.cpp
  src/axom/quest/interface/inout.hpp
Labels: bug, Testing, Fortan

#1290 Renames some bit/byte operations to match newer C++ standards
  RELEASE-NOTES.md
  src/axom/core/FlatMap.hpp
  src/axom/core/tests/CMakeLists.txt
  src/axom/core/tests/core_bit_utilities.hpp
  src/axom/core/tests/utils_endianness.hpp
  src/axom/core/utilities/BitUtilities.hpp
  src/axom/core/utilities/Utilities.hpp
  src/axom/lumberjack/TextTagCombiner.hpp
  src/axom/lumberjack/tests/lumberjack_TextTagCombiner.hpp
  src/axom/quest/examples/quest_proe_bbox.cpp
  src/axom/quest/readers/STLReader.cpp
  src/axom/slam/BitSet.cpp
  src/axom/spin/ImplicitGrid.hpp
  src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
Labels: maintenance

#1263 Improve marching cubes performance on GPUs
  RELEASE-NOTES.md
  src/axom/core/Array.hpp
  src/axom/mint/mesh/internal/ConnectivityArrayHelpers.hpp
  src/axom/primal/geometry/Vector.hpp
  src/axom/quest/ArrayIndexer.hpp
  src/axom/quest/CMakeLists.txt
  src/axom/quest/DistributedClosestPoint.hpp
  src/axom/quest/MarchingCubes.cpp
  src/axom/quest/MarchingCubes.hpp
  src/axom/quest/MeshViewUtil.hpp
  src/axom/quest/detail/MarchingCubesFullParallel.hpp
  src/axom/quest/detail/MarchingCubesHybridParallel.hpp
  src/axom/quest/detail/MarchingCubesImpl.hpp
  src/axom/quest/detail/MarchingCubesSingleDomain.cpp
  src/axom/quest/detail/MarchingCubesSingleDomain.hpp
  src/axom/quest/examples/quest_marching_cubes_example.cpp
  src/axom/quest/tests/quest_array_indexer.cpp
  src/axom/quest/tests/quest_mesh_view_util.cpp
Labels: Quest, GPU, cuda, high priority, Performance

#1293 using-with-cmake example cmake version
  .gitlab/build_rzansel.yml
  src/examples/using-with-cmake/CMakeLists.txt
Labels: CI

#1299 Use `tee` instead of reading log files to the screen in Build scripts
  scripts/llnl_scripts/llnl_lc_build_tools.py
Labels: CI, Build system

#1301 Updates vcpkg TPL build on Windows
  .uberenv_config.json
  RELEASE-NOTES.md
  scripts/vcpkg_ports/axom/vcpkg.json
  scripts/vcpkg_ports/blt/portfile.cmake
  scripts/vcpkg_ports/blt/vcpkg.json
  scripts/vcpkg_ports/camp/portfile.cmake
  scripts/vcpkg_ports/camp/vcpkg.json
  scripts/vcpkg_ports/conduit/portfile.cmake
  scripts/vcpkg_ports/conduit/vcpkg.json
  scripts/vcpkg_ports/mfem/export-extern-vars.patch
  scripts/vcpkg_ports/mfem/portfile.cmake
  scripts/vcpkg_ports/mfem/vcpkg.json
  scripts/vcpkg_ports/raja/portfile.cmake
  scripts/vcpkg_ports/raja/vcpkg.json
  scripts/vcpkg_ports/umpire/portfile.cmake
  scripts/vcpkg_ports/umpire/vcpkg.json
  src/axom/primal/operators/winding_number.hpp
  src/axom/primal/tests/primal_winding_number.cpp
  src/axom/quest/detail/MarchingCubesImpl.hpp
Labels: TPL, maintenance, Windows

#1295 HIP intrinsics, candidate examples init change
  src/axom/core/utilities/BitUtilities.hpp
  src/axom/quest/examples/quest_candidates_example.cpp
Labels: Core, Quest, Hip

#1291 Add support for caliper and adiak dependencies
  RELEASE-NOTES.md
  azure-pipelines.yml
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake
  host-configs/quartz-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/quartz-toss_4_x86_64_ib-gcc@10.3.1.cmake
  host-configs/quartz-toss_4_x86_64_ib-intel@2022.1.0.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-gcc@10.3.1.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-intel@2022.1.0.cmake
  host-configs/rzvernal-toss_4_x86_64_ib_cray-clang@16.0.0_hip.cmake
  host-configs/rzwhippet-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/rzwhippet-toss_4_x86_64_ib-gcc@10.3.1.cmake
  host-configs/rzwhippet-toss_4_x86_64_ib-intel@2022.1.0.cmake
  host-configs/tioga-toss_4_x86_64_ib_cray-clang@16.0.0_hip.cmake
  scripts/docker/dockerfile_clang-10
  scripts/docker/dockerfile_gcc-11
  scripts/docker/dockerfile_gcc-9_cuda-11
  scripts/llnl_scripts/find_unused_tpl_dirs.py
  scripts/llnl_scripts/fix_permissions.py
  scripts/llnl_scripts/move_unused_tpl_dirs_to_graveyard.py
  scripts/spack/configs/blueos_3_ppc64le_ib_p9/spack.yaml
  scripts/spack/configs/docker/ubuntu20/spack.yaml
  scripts/spack/configs/docker/ubuntu20_cuda/spack.yaml
  scripts/spack/configs/linux_ubuntu_20/spack.yaml
  scripts/spack/configs/toss_4_x86_64_ib/spack.yaml
  scripts/spack/configs/toss_4_x86_64_ib_cray/spack.yaml
  scripts/spack/packages/axom/package.py
  scripts/spack/specs.json
  src/axom/config.hpp.in
  src/axom/core/tests/core_about.hpp
  src/axom/core/utilities/About.cpp.in
  src/axom/core/utilities/AnnotationMacros.hpp
  src/cmake/AxomConfig.cmake
  src/cmake/axom-config.cmake.in
  src/cmake/thirdparty/SetupAxomThirdParty.cmake
  src/thirdparty/tests/CMakeLists.txt
  src/thirdparty/tests/adiak_smoke.cpp
  src/thirdparty/tests/caliper_smoke.cpp
Labels: TPL, CI, Build system

#1304 Array emplace_back warning and possible link error
  src/axom/quest/ArrayIndexer.hpp
  src/axom/quest/MarchingCubes.cpp
Labels: bug
